all:
  vars:
    control_plane_endpoint: 172.16.100.1
    load_balancer_ip_pool:
      - 172.16.100.32/27
metal:
  children:
    masters:
      hosts:
        mc5-1: {ansible_host: 172.16.100.201, mac: '98:fa:9b:6e:0d:e8', disk: nvme0n1, network_interface: eno1}
        mc4-1: {ansible_host: 172.16.100.202, mac: '98:fa:9b:bc:12:6c', disk: nvme0n1, network_interface: eno1}
        mc4-2: {ansible_host: 172.16.100.203, mac: '98:fa:9b:bc:12:f8', disk: nvme0n1, network_interface: eno1}
    #workers:
      #hosts:
        #metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
